### ISSUE TITLE
Prismic.io in Angular 2

### ISSUE THREAD

**Issue by julianlecalvez** [prismicio/javascript-kit#120]
Hello !

I'm trying to find a way to import this JS kit in my Angular 2 project.
Is there a way to do so ? I tried to understand the Angular2-starter but it's not documented to do it on an existing project.

I want to know if there is a way to import node modules directly into Angular2 ?

Thanks in advance !

Julian

**Comment by erwan** [comment]
Hi,

Most of the time you'll be using Angular 2 with Webpack or Browserify, so you can  just install the kit using npm:

```
npm install prismic.io --save
```

The Angular 2 starter is not documented because it's not officially released, it's work in progress. You can use it as an example of usage to include prismic.io in an existing project however.

Also, if you're using Typescript (which is common with Angular 2), you need a definition file.  The one included in the Angular 2 starter is incomplete:

https://github.com/prismicio/angular2-starter/blob/master/typings/prismic.io.d.ts

So if you use it, you might need to extend it or some functions may not be recognized by the compiler.

Alternatively, you can provide a generic definition file like this one:

```
declare module "prismic.io" {
  let Prismic: any
}
```

**Comment by julianlecalvez** [comment]
Hi erwan,

Thank you for your answer !
I guess I'm missing something in my configuration. 
I installed the npm module with your command line, and then I declared the prismic.io.d.ts file (the generic one and the one in the starter kit). 

Finally, I tried to import Prismic in my home.ts file : 
`import { Prismic } from "prismic.io";`

When I serve the project, I still get an error : 
`...../home.ts(4,25): Error TS2307: Cannot find module 'prismic.io'.`

Thanks !

**Comment by julianlecalvez** [comment]
It seems that my d.ts file is not loaded when it compiles (I put a wrong code inside to generate an error but nothing happened, but it does in another d.ts)

**Comment by erwan** [comment]
Yes, this error message means the d.ts file is not loaded.

If the syntax is correct, and it's declared in tsconfig.json it should work. At this point it's not really specific to prismic.io but it's a typescript issue, maybe you'll have more luck getting help about that in a typescript-related community.
